
package es.greenaall.gos.gf.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-05T12:16:29.667+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "CtrError", targetNamespace = "http://ws.gf.gos.greenaall.es")
public class CtrError_Exception extends java.lang.Exception {

    private es.greenaall.gos.gf.ws.CtrError faultInfo;

    public CtrError_Exception() {
        super();
    }

    public CtrError_Exception(String message) {
        super(message);
    }

    public CtrError_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CtrError_Exception(String message, es.greenaall.gos.gf.ws.CtrError ctrError) {
        super(message);
        this.faultInfo = ctrError;
    }

    public CtrError_Exception(String message, es.greenaall.gos.gf.ws.CtrError ctrError, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = ctrError;
    }

    public es.greenaall.gos.gf.ws.CtrError getFaultInfo() {
        return this.faultInfo;
    }
}
