package es.greenaall.gos.gf.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-05T12:16:29.674+01:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://ws.gf.gos.greenaall.es", name = "GestionTributosPortType")
@XmlSeeAlso({java.rmi.xsd.ObjectFactory.class, es.greenaall.gos.sa.dto.xsd.ObjectFactory.class, es.greenaall.gos.gf.ws.request.xsd.ObjectFactory.class, java.io.xsd.ObjectFactory.class, es.greenaall.gos.ur.ws.request.xsd.ObjectFactory.class, es.greenaall.gos.gf.ws.response.xsd.ObjectFactory.class, es.greenaall.gos.gf.dto.xsd.ObjectFactory.class, ObjectFactory.class, es.greenaall.gos.pe.dto.ws.xsd.ObjectFactory.class, es.greenaall.util.comun.excepciones.xsd.ObjectFactory.class, es.greenaall.gos.ge.ws.xsd.ObjectFactory.class, es.greenaall.gos.gf.ws.xsd.ObjectFactory.class, es.greenaall.gos.ge.dto.xsd.ObjectFactory.class, es.greenaall.gos.gf.dto.ws.xsd.ObjectFactory.class, es.greenaall.gos.gf.ws.dto.xsd.ObjectFactory.class})
public interface GestionTributosPortType {

    @WebMethod(action = "urn:consultaOrdenazaFiscal")
    @Action(input = "urn:consultaOrdenazaFiscal", output = "urn:consultaOrdenazaFiscalResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaOrdenazaFiscalRemoteException")})
    @RequestWrapper(localName = "consultaOrdenazaFiscal", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaOrdenazaFiscal")
    @ResponseWrapper(localName = "consultaOrdenazaFiscalResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaOrdenazaFiscalResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaOrdenanzaFiscalResponse consultaOrdenazaFiscal(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaOrdenanzaFiscalRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaVolante")
    @Action(input = "urn:altaVolante", output = "urn:altaVolanteResponse")
    @RequestWrapper(localName = "altaVolante", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVolante")
    @ResponseWrapper(localName = "altaVolanteResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVolanteResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.VolanteOut altaVolante(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarVolanteRequest request
    );

    @WebMethod(action = "urn:generarTEU")
    @Action(input = "urn:generarTEU", output = "urn:generarTEUResponse")
    @RequestWrapper(localName = "generarTEU", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.GenerarTEU")
    @ResponseWrapper(localName = "generarTEUResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.GenerarTEUResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.FicheroTeuResponse generarTEU(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.FicheroTeuRequest request
    );

    @WebMethod(action = "urn:consultaProcedimientos")
    @Action(input = "urn:consultaProcedimientos", output = "urn:consultaProcedimientosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaProcedimientosRemoteException")})
    @RequestWrapper(localName = "consultaProcedimientos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaProcedimientos")
    @ResponseWrapper(localName = "consultaProcedimientosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaProcedimientosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaProcedimientosResponse consultaProcedimientos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaProcedimientosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaObjetosTributarios")
    @Action(input = "urn:consultaObjetosTributarios", output = "urn:consultaObjetosTributariosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaObjetosTributariosRemoteException")})
    @RequestWrapper(localName = "consultaObjetosTributarios", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaObjetosTributarios")
    @ResponseWrapper(localName = "consultaObjetosTributariosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaObjetosTributariosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetosTributariosResponse consultaObjetosTributarios(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetosTributariosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaCitaInternet")
    @Action(input = "urn:consultaCitaInternet", output = "urn:consultaCitaInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaCitaInternetRemoteException")})
    @RequestWrapper(localName = "consultaCitaInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaCitaInternet")
    @ResponseWrapper(localName = "consultaCitaInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaCitaInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaCitaInternetResponse consultaCitaInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaCitaInternetRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaVehiculos")
    @Action(input = "urn:consultaVehiculos", output = "urn:consultaVehiculosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaVehiculosRemoteException")})
    @RequestWrapper(localName = "consultaVehiculos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaVehiculos")
    @ResponseWrapper(localName = "consultaVehiculosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaVehiculosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaVehiculosResponse consultaVehiculos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaVehiculosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarReciboInternet2")
    @Action(input = "urn:actualizarReciboInternet2", output = "urn:actualizarReciboInternet2Response")
    @RequestWrapper(localName = "actualizarReciboInternet2", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboInternet2")
    @ResponseWrapper(localName = "actualizarReciboInternet2Response", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboInternet2Response")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ActualizarReciboInternet2Response actualizarReciboInternet2(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ActualizarReciboInternet2Request request
    );

    @WebMethod(action = "urn:consultaNotificaciones")
    @Action(input = "urn:consultaNotificaciones", output = "urn:consultaNotificacionesResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaNotificacionesRemoteException")})
    @RequestWrapper(localName = "consultaNotificaciones", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaNotificaciones")
    @ResponseWrapper(localName = "consultaNotificacionesResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaNotificacionesResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaNotificacionesResponse consultaNotificaciones(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaNotificacionesRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaExpediente")
    @Action(input = "urn:consultaExpediente", output = "urn:consultaExpedienteResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaExpedienteRemoteException")})
    @RequestWrapper(localName = "consultaExpediente", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaExpediente")
    @ResponseWrapper(localName = "consultaExpedienteResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaExpedienteResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaExpedienteResponse consultaExpediente(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaTramitacionRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaObjetoTributarioMd")
    @Action(input = "urn:altaObjetoTributarioMd", output = "urn:altaObjetoTributarioMdResponse")
    @RequestWrapper(localName = "altaObjetoTributarioMd", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaObjetoTributarioMd")
    @ResponseWrapper(localName = "altaObjetoTributarioMdResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaObjetoTributarioMdResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.ObjetoTributarioMdOut altaObjetoTributarioMd(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarObjetoTributarioMdRequest request
    );

    @WebMethod(action = "urn:consultaAutoLiquidacion")
    @Action(input = "urn:consultaAutoLiquidacion", output = "urn:consultaAutoLiquidacionResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaAutoLiquidacionRemoteException")})
    @RequestWrapper(localName = "consultaAutoLiquidacion", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAutoLiquidacion")
    @ResponseWrapper(localName = "consultaAutoLiquidacionResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAutoLiquidacionResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaAutoLiquidacionResponse consultaAutoLiquidacion(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaAutoLiquidacionRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaCobroContabilidad")
    @Action(input = "urn:altaCobroContabilidad", output = "urn:altaCobroContabilidadResponse")
    @RequestWrapper(localName = "altaCobroContabilidad", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaCobroContabilidad")
    @ResponseWrapper(localName = "altaCobroContabilidadResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaCobroContabilidadResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AltaCobroContabilidadResponse altaCobroContabilidad(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.CobroContabilidadRequest request
    );

    @WebMethod(action = "urn:altaCitaInternet")
    @Action(input = "urn:altaCitaInternet", output = "urn:altaCitaInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:altaCitaInternetRemoteException")})
    @RequestWrapper(localName = "altaCitaInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaCitaInternet")
    @ResponseWrapper(localName = "altaCitaInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaCitaInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AltaCitaInternetResponse altaCitaInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AltaCitaInternetRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaRecibo")
    @Action(input = "urn:altaRecibo", output = "urn:altaReciboResponse")
    @RequestWrapper(localName = "altaRecibo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaRecibo")
    @ResponseWrapper(localName = "altaReciboResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaReciboResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.ReciboOut altaRecibo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarReciboRequest request
    );

    @WebMethod(action = "urn:consultaFacturas")
    @Action(input = "urn:consultaFacturas", output = "urn:consultaFacturasResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaFacturasRemoteException")})
    @RequestWrapper(localName = "consultaFacturas", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaFacturas")
    @ResponseWrapper(localName = "consultaFacturasResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaFacturasResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaFacturasResponse consultaFacturas(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaFacturaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaTributoGUI")
    @Action(input = "urn:altaTributoGUI", output = "urn:altaTributoGUIResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:altaTributoGUIRemoteException")})
    @RequestWrapper(localName = "altaTributoGUI", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaTributoGUI")
    @ResponseWrapper(localName = "altaTributoGUIResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaTributoGUIResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public java.lang.String altaTributoGUI(

        @WebParam(name = "datosConexion", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.xsd.DatoConexion datosConexion
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboRustica")
    @Action(input = "urn:consultaReciboRustica", output = "urn:consultaReciboRusticaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboRusticaRemoteException")})
    @RequestWrapper(localName = "consultaReciboRustica", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboRustica")
    @ResponseWrapper(localName = "consultaReciboRusticaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboRusticaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoRusticaResponse consultaReciboRustica(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoRusticaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaRegistroEfirma")
    @Action(input = "urn:altaRegistroEfirma", output = "urn:altaRegistroEfirmaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:altaRegistroEfirmaRemoteException")})
    @RequestWrapper(localName = "altaRegistroEfirma", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaRegistroEfirma")
    @ResponseWrapper(localName = "altaRegistroEfirmaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaRegistroEfirmaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AltaRegistroResponse altaRegistroEfirma(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AltaRegistroRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:dameCentrosCita")
    @Action(input = "urn:dameCentrosCita", output = "urn:dameCentrosCitaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:dameCentrosCitaRemoteException")})
    @RequestWrapper(localName = "dameCentrosCita", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameCentrosCita")
    @ResponseWrapper(localName = "dameCentrosCitaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameCentrosCitaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaCentrosResponse dameCentrosCita(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaCentrosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaAutoliquidacionInternet")
    @Action(input = "urn:consultaAutoliquidacionInternet", output = "urn:consultaAutoliquidacionInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaAutoliquidacionInternetRemoteException")})
    @RequestWrapper(localName = "consultaAutoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAutoliquidacionInternet")
    @ResponseWrapper(localName = "consultaAutoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaAutoLiquidacionInternetResponse consultaAutoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaAutoLiquidacionInternetRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaAplicacionMen")
    @Action(input = "urn:consultaAplicacionMen", output = "urn:consultaAplicacionMenResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaAplicacionMenRemoteException")})
    @RequestWrapper(localName = "consultaAplicacionMen", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAplicacionMen")
    @ResponseWrapper(localName = "consultaAplicacionMenResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaAplicacionMenResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaAplicacionesResponse consultaAplicacionMen(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaAplicacionesRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaJusGastosMen")
    @Action(input = "urn:consultaJusGastosMen", output = "urn:consultaJusGastosMenResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaJusGastosMenRemoteException")})
    @RequestWrapper(localName = "consultaJusGastosMen", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaJusGastosMen")
    @ResponseWrapper(localName = "consultaJusGastosMenResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaJusGastosMenResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaJustificantesGastosResponse consultaJusGastosMen(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaJustificantesGastosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaOperacionMen")
    @Action(input = "urn:consultaOperacionMen", output = "urn:consultaOperacionMenResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaOperacionMenRemoteException")})
    @RequestWrapper(localName = "consultaOperacionMen", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaOperacionMen")
    @ResponseWrapper(localName = "consultaOperacionMenResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaOperacionMenResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaOperacionesResponse consultaOperacionMen(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaOperacionesRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaArchivo")
    @Action(input = "urn:altaArchivo", output = "urn:altaArchivoResponse")
    @RequestWrapper(localName = "altaArchivo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaArchivo")
    @ResponseWrapper(localName = "altaArchivoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaArchivoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.ArchivoOut altaArchivo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarArchivoRequest request
    );

    @WebMethod(action = "urn:desconexionAutoLiquidaciones")
    @Action(input = "urn:desconexionAutoLiquidaciones", output = "urn:desconexionAutoLiquidacionesResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:desconexionAutoLiquidacionesRemoteException")})
    @RequestWrapper(localName = "desconexionAutoLiquidaciones", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DesconexionAutoLiquidaciones")
    @ResponseWrapper(localName = "desconexionAutoLiquidacionesResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DesconexionAutoLiquidacionesResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.DesconexionAutoLiquidacionesResponse desconexionAutoLiquidaciones(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.DesconexionAutoLiquidacioneRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultarTributosGUI")
    @Action(input = "urn:consultarTributosGUI", output = "urn:consultarTributosGUIResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultarTributosGUIRemoteException")})
    @RequestWrapper(localName = "consultarTributosGUI", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultarTributosGUI")
    @ResponseWrapper(localName = "consultarTributosGUIResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultarTributosGUIResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public java.lang.String consultarTributosGUI(

        @WebParam(name = "objetoTributario", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.dto.xsd.ObjetoTributarioRc objetoTributario,
        @WebParam(name = "datosConexion", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.xsd.DatoConexion datosConexion
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboPlus")
    @Action(input = "urn:consultaReciboPlus", output = "urn:consultaReciboPlusResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboPlusRemoteException")})
    @RequestWrapper(localName = "consultaReciboPlus", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboPlus")
    @ResponseWrapper(localName = "consultaReciboPlusResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboPlusResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoPlusResponse consultaReciboPlus(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoPlusRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:dameCentrosHorario")
    @Action(input = "urn:dameCentrosHorario", output = "urn:dameCentrosHorarioResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:dameCentrosHorarioRemoteException")})
    @RequestWrapper(localName = "dameCentrosHorario", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameCentrosHorario")
    @ResponseWrapper(localName = "dameCentrosHorarioResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameCentrosHorarioResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaCentrosHorarioResponse dameCentrosHorario(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaCentrosHorarioRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarEstadoDocumento")
    @Action(input = "urn:actualizarEstadoDocumento", output = "urn:actualizarEstadoDocumentoResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:actualizarEstadoDocumentoRemoteException")})
    @RequestWrapper(localName = "actualizarEstadoDocumento", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarEstadoDocumento")
    @ResponseWrapper(localName = "actualizarEstadoDocumentoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarEstadoDocumentoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.ge.ws.xsd.RespuestaActualizacion actualizarEstadoDocumento(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.RespuestaActualizacionRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboPlusvalia")
    @Action(input = "urn:consultaReciboPlusvalia", output = "urn:consultaReciboPlusvaliaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboPlusvaliaRemoteException")})
    @RequestWrapper(localName = "consultaReciboPlusvalia", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboPlusvalia")
    @ResponseWrapper(localName = "consultaReciboPlusvaliaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboPlusvaliaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoPlusvaliaResponse consultaReciboPlusvalia(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoPlusvaliaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboVehiculo")
    @Action(input = "urn:consultaReciboVehiculo", output = "urn:consultaReciboVehiculoResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboVehiculoRemoteException")})
    @RequestWrapper(localName = "consultaReciboVehiculo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboVehiculo")
    @ResponseWrapper(localName = "consultaReciboVehiculoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboVehiculoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoVehiculoResponse consultaReciboVehiculo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoVehiculoRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaInfracciones")
    @Action(input = "urn:consultaInfracciones", output = "urn:consultaInfraccionesResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaInfraccionesRemoteException")})
    @RequestWrapper(localName = "consultaInfracciones", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaInfracciones")
    @ResponseWrapper(localName = "consultaInfraccionesResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaInfraccionesResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaInfraccionesResponse consultaInfracciones(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaInfraccionesRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboIae")
    @Action(input = "urn:consultaReciboIae", output = "urn:consultaReciboIaeResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboIaeRemoteException")})
    @RequestWrapper(localName = "consultaReciboIae", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboIae")
    @ResponseWrapper(localName = "consultaReciboIaeResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboIaeResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoIaeResponse consultaReciboIae(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoIaeRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:envioCorreo")
    @Action(input = "urn:envioCorreo", output = "urn:envioCorreoResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:envioCorreoRemoteException")})
    @RequestWrapper(localName = "envioCorreo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.EnvioCorreo")
    @ResponseWrapper(localName = "envioCorreoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.EnvioCorreoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.EnvioCorreoResponse envioCorreo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.EnvioCorreoRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultarLiquidacionesTributosGUI")
    @Action(input = "urn:consultarLiquidacionesTributosGUI", output = "urn:consultarLiquidacionesTributosGUIResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultarLiquidacionesTributosGUIRemoteException")})
    @RequestWrapper(localName = "consultarLiquidacionesTributosGUI", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultarLiquidacionesTributosGUI")
    @ResponseWrapper(localName = "consultarLiquidacionesTributosGUIResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultarLiquidacionesTributosGUIResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public java.lang.String consultarLiquidacionesTributosGUI(

        @WebParam(name = "liquidacion", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.dto.xsd.LiquidacionRc liquidacion,
        @WebParam(name = "datosConexion", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.xsd.DatoConexion datosConexion
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaRecibos")
    @Action(input = "urn:consultaRecibos", output = "urn:consultaRecibosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaRecibosRemoteException")})
    @RequestWrapper(localName = "consultaRecibos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaRecibos")
    @ResponseWrapper(localName = "consultaRecibosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaRecibosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaRecibosResponse consultaRecibos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaRecibosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaTiposObjetosTributarios")
    @Action(input = "urn:consultaTiposObjetosTributarios", output = "urn:consultaTiposObjetosTributariosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaTiposObjetosTributariosRemoteException")})
    @RequestWrapper(localName = "consultaTiposObjetosTributarios", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTiposObjetosTributarios")
    @ResponseWrapper(localName = "consultaTiposObjetosTributariosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTiposObjetosTributariosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaTiposObjetosTributariosResponse consultaTiposObjetosTributarios(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaTipoObjetoTributarioRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboCementerio")
    @Action(input = "urn:consultaReciboCementerio", output = "urn:consultaReciboCementerioResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboCementerioRemoteException")})
    @RequestWrapper(localName = "consultaReciboCementerio", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboCementerio")
    @ResponseWrapper(localName = "consultaReciboCementerioResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboCementerioResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoCementerioResponse consultaReciboCementerio(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoCementerioRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaNotificacion")
    @Action(input = "urn:altaNotificacion", output = "urn:altaNotificacionResponse")
    @RequestWrapper(localName = "altaNotificacion", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaNotificacion")
    @ResponseWrapper(localName = "altaNotificacionResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaNotificacionResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.NotificacionOut altaNotificacion(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarNotificacionRequest request
    );

    @WebMethod(action = "urn:validarUsuarioGos")
    @Action(input = "urn:validarUsuarioGos", output = "urn:validarUsuarioGosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:validarUsuarioGosRemoteException")})
    @RequestWrapper(localName = "validarUsuarioGos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ValidarUsuarioGos")
    @ResponseWrapper(localName = "validarUsuarioGosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ValidarUsuarioGosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ValidarUsuarioGosResponse validarUsuarioGos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ValidarUsuarioGosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaVehiculo")
    @Action(input = "urn:altaVehiculo", output = "urn:altaVehiculoResponse")
    @RequestWrapper(localName = "altaVehiculo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVehiculo")
    @ResponseWrapper(localName = "altaVehiculoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVehiculoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.VehiculoOut altaVehiculo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarVehiculoRequest request
    );

    @WebMethod(action = "urn:consultaModalidadProcedimientos")
    @Action(input = "urn:consultaModalidadProcedimientos", output = "urn:consultaModalidadProcedimientosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaModalidadProcedimientosRemoteException")})
    @RequestWrapper(localName = "consultaModalidadProcedimientos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaModalidadProcedimientos")
    @ResponseWrapper(localName = "consultaModalidadProcedimientosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaModalidadProcedimientosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaMateriaProcedimientosResponse consultaModalidadProcedimientos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaModalidadProcedimientosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:anularCitaInternet")
    @Action(input = "urn:anularCitaInternet", output = "urn:anularCitaInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:anularCitaInternetRemoteException")})
    @RequestWrapper(localName = "anularCitaInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AnularCitaInternet")
    @ResponseWrapper(localName = "anularCitaInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AnularCitaInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AnularCitaInternetResponse anularCitaInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AnularCitaInternetRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:dameParametroSistema")
    @Action(input = "urn:dameParametroSistema", output = "urn:dameParametroSistemaResponse", fault = {@FaultAction(className = CtrError_Exception.class, value = "urn:dameParametroSistemaCtrError")})
    @RequestWrapper(localName = "dameParametroSistema", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameParametroSistema")
    @ResponseWrapper(localName = "dameParametroSistemaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DameParametroSistemaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public java.lang.String dameParametroSistema(

        @WebParam(name = "sCodEntid", targetNamespace = "http://ws.gf.gos.greenaall.es")
        java.lang.Short sCodEntid,
        @WebParam(name = "sAnno", targetNamespace = "http://ws.gf.gos.greenaall.es")
        java.lang.Short sAnno,
        @WebParam(name = "sIdioma", targetNamespace = "http://ws.gf.gos.greenaall.es")
        java.lang.String sIdioma,
        @WebParam(name = "sNumValor", targetNamespace = "http://ws.gf.gos.greenaall.es")
        java.lang.Short sNumValor
    ) throws CtrError_Exception;

    @WebMethod(action = "urn:descargarArchivo")
    @Action(input = "urn:descargarArchivo", output = "urn:descargarArchivoResponse")
    @RequestWrapper(localName = "descargarArchivo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DescargarArchivo")
    @ResponseWrapper(localName = "descargarArchivoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.DescargarArchivoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.DescargarArchivoServidorResponse descargarArchivo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.DescargarArchivoServidorRequest request
    );

    @WebMethod(action = "urn:altaVolanteImagen")
    @Action(input = "urn:altaVolanteImagen", output = "urn:altaVolanteImagenResponse")
    @RequestWrapper(localName = "altaVolanteImagen", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVolanteImagen")
    @ResponseWrapper(localName = "altaVolanteImagenResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaVolanteImagenResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.VolanteOut altaVolanteImagen(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarVolanteImagenRequest request
    );

    @WebMethod(action = "urn:consultaTerritorio")
    @Action(input = "urn:consultaTerritorio", output = "urn:consultaTerritorioResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaTerritorioRemoteException")})
    @RequestWrapper(localName = "consultaTerritorio", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTerritorio")
    @ResponseWrapper(localName = "consultaTerritorioResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTerritorioResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaTerritorioResponse consultaTerritorio(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaTerritorioRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarRecibo")
    @Action(input = "urn:actualizarRecibo", output = "urn:actualizarReciboResponse")
    @RequestWrapper(localName = "actualizarRecibo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarRecibo")
    @ResponseWrapper(localName = "actualizarReciboResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ActualizarReciboResponse actualizarRecibo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ActualizarReciboRequest request
    );

    @WebMethod(action = "urn:consultaArchivo")
    @Action(input = "urn:consultaArchivo", output = "urn:consultaArchivoResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaArchivoRemoteException")})
    @RequestWrapper(localName = "consultaArchivo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaArchivo")
    @ResponseWrapper(localName = "consultaArchivoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaArchivoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaArchivoResponse consultaArchivo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaArchivoRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboLpo")
    @Action(input = "urn:consultaReciboLpo", output = "urn:consultaReciboLpoResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboLpoRemoteException")})
    @RequestWrapper(localName = "consultaReciboLpo", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboLpo")
    @ResponseWrapper(localName = "consultaReciboLpoResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboLpoResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoLpoResponse consultaReciboLpo(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoLpoRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboIcio")
    @Action(input = "urn:consultaReciboIcio", output = "urn:consultaReciboIcioResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboIcioRemoteException")})
    @RequestWrapper(localName = "consultaReciboIcio", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboIcio")
    @ResponseWrapper(localName = "consultaReciboIcioResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboIcioResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoIcioResponse consultaReciboIcio(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoIcioRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaFestivos")
    @Action(input = "urn:consultaFestivos", output = "urn:consultaFestivosResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaFestivosRemoteException")})
    @RequestWrapper(localName = "consultaFestivos", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaFestivos")
    @ResponseWrapper(localName = "consultaFestivosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaFestivosResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaFestivosResponse consultaFestivos(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaFestivosRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaObjetoMd")
    @Action(input = "urn:consultaObjetoMd", output = "urn:consultaObjetoMdResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaObjetoMdRemoteException")})
    @RequestWrapper(localName = "consultaObjetoMd", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaObjetoMd")
    @ResponseWrapper(localName = "consultaObjetoMdResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaObjetoMdResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoMdResponse consultaObjetoMd(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoMdRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarReciboInternet")
    @Action(input = "urn:actualizarReciboInternet", output = "urn:actualizarReciboInternetResponse")
    @RequestWrapper(localName = "actualizarReciboInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboInternet")
    @ResponseWrapper(localName = "actualizarReciboInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ActualizarReciboInternetResponse actualizarReciboInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ActualizarReciboInternetRequest request
    );

    @WebMethod(action = "urn:altaObjetoTributario")
    @Action(input = "urn:altaObjetoTributario", output = "urn:altaObjetoTributarioResponse")
    @RequestWrapper(localName = "altaObjetoTributario", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaObjetoTributario")
    @ResponseWrapper(localName = "altaObjetoTributarioResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaObjetoTributarioResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.ObjetoTributarioOut altaObjetoTributario(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.GenerarObjetoTributarioRequest request
    );

    @WebMethod(action = "urn:consultaLiquidaciones")
    @Action(input = "urn:consultaLiquidaciones", output = "urn:consultaLiquidacionesResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaLiquidacionesRemoteException")})
    @RequestWrapper(localName = "consultaLiquidaciones", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaLiquidaciones")
    @ResponseWrapper(localName = "consultaLiquidacionesResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaLiquidacionesResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaLiquidacionesResponse consultaLiquidaciones(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaLiquidacionesRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaMetadatosGrupoAtrib")
    @Action(input = "urn:consultaMetadatosGrupoAtrib", output = "urn:consultaMetadatosGrupoAtribResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaMetadatosGrupoAtribRemoteException")})
    @RequestWrapper(localName = "consultaMetadatosGrupoAtrib", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaMetadatosGrupoAtrib")
    @ResponseWrapper(localName = "consultaMetadatosGrupoAtribResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaMetadatosGrupoAtribResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaMetadatosGrupoAtribResponse consultaMetadatosGrupoAtrib(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaMetadatosGrupoAtribRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:altaAutoliquidacionInternet")
    @Action(input = "urn:altaAutoliquidacionInternet", output = "urn:altaAutoliquidacionInternetResponse")
    @RequestWrapper(localName = "altaAutoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaAutoliquidacionInternet")
    @ResponseWrapper(localName = "altaAutoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaAutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.AutoliquidacionInternetOut altaAutoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AutoliquidacionesInternetRecaudacionRequest request
    );

    @WebMethod(action = "urn:consultaReciboMulta")
    @Action(input = "urn:consultaReciboMulta", output = "urn:consultaReciboMultaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboMultaRemoteException")})
    @RequestWrapper(localName = "consultaReciboMulta", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboMulta")
    @ResponseWrapper(localName = "consultaReciboMultaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboMultaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoMultaResponse consultaReciboMulta(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoMultaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarReciboPT")
    @Action(input = "urn:actualizarReciboPT", output = "urn:actualizarReciboPTResponse")
    @RequestWrapper(localName = "actualizarReciboPT", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboPT")
    @ResponseWrapper(localName = "actualizarReciboPTResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarReciboPTResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ActualizarReciboResponse actualizarReciboPT(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ActualizarReciboPTRequest request
    );

    @WebMethod(action = "urn:obtenerAutoliquidacionInternet")
    @Action(input = "urn:obtenerAutoliquidacionInternet", output = "urn:obtenerAutoliquidacionInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:obtenerAutoliquidacionInternetRemoteException")})
    @RequestWrapper(localName = "obtenerAutoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ObtenerAutoliquidacionInternet")
    @ResponseWrapper(localName = "obtenerAutoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ObtenerAutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AutoLiquidacionInternetHResponse obtenerAutoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AutoLiquidacionInternetHRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:validarAgentePolicia")
    @Action(input = "urn:validarAgentePolicia", output = "urn:validarAgentePoliciaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:validarAgentePoliciaRemoteException")})
    @RequestWrapper(localName = "validarAgentePolicia", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ValidarAgentePolicia")
    @ResponseWrapper(localName = "validarAgentePoliciaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ValidarAgentePoliciaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ValidarAgentePoliciaResponse validarAgentePolicia(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ValidaAgentePoliciaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarAutoliquidacionInternet")
    @Action(input = "urn:actualizarAutoliquidacionInternet", output = "urn:actualizarAutoliquidacionInternetResponse")
    @RequestWrapper(localName = "actualizarAutoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarAutoliquidacionInternet")
    @ResponseWrapper(localName = "actualizarAutoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarAutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.AutoliquidacionInternetOut actualizarAutoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AutoliquidacionesInternetRecaudacionRequest request
    );

    @WebMethod(action = "urn:consultaReciboAgua")
    @Action(input = "urn:consultaReciboAgua", output = "urn:consultaReciboAguaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboAguaRemoteException")})
    @RequestWrapper(localName = "consultaReciboAgua", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboAgua")
    @ResponseWrapper(localName = "consultaReciboAguaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboAguaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoAguaResponse consultaReciboAgua(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoAguaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:actualizarNotificacion")
    @Action(input = "urn:actualizarNotificacion", output = "urn:actualizarNotificacionResponse")
    @RequestWrapper(localName = "actualizarNotificacion", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarNotificacion")
    @ResponseWrapper(localName = "actualizarNotificacionResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ActualizarNotificacionResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ActualizarNotificacionResponse actualizarNotificacion(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ActualizarNotificacionRequest request
    );

    @WebMethod(action = "urn:borrarAutoliquidacionInternet")
    @Action(input = "urn:borrarAutoliquidacionInternet", output = "urn:borrarAutoliquidacionInternetResponse")
    @RequestWrapper(localName = "borrarAutoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.BorrarAutoliquidacionInternet")
    @ResponseWrapper(localName = "borrarAutoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.BorrarAutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.AutoliquidacionInternetOut borrarAutoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AutoliquidacionesInternetRecaudacionRequest request
    );

    @WebMethod(action = "urn:altaRegistro")
    @Action(input = "urn:altaRegistro", output = "urn:altaRegistroResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:altaRegistroRemoteException")})
    @RequestWrapper(localName = "altaRegistro", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaRegistro")
    @ResponseWrapper(localName = "altaRegistroResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AltaRegistroResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.AltaRegistroResponse altaRegistro(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AltaRegistroRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:autoliquidacionInternet")
    @Action(input = "urn:autoliquidacionInternet", output = "urn:autoliquidacionInternetResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:autoliquidacionInternetRemoteException")})
    @RequestWrapper(localName = "autoliquidacionInternet", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AutoliquidacionInternet")
    @ResponseWrapper(localName = "autoliquidacionInternetResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.AutoliquidacionInternetResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.dto.xsd.CalcularImporteAutoliquidacionResponse autoliquidacionInternet(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.AutoliquidacionInternetRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaTramitacion")
    @Action(input = "urn:consultaTramitacion", output = "urn:consultaTramitacionResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaTramitacionRemoteException")})
    @RequestWrapper(localName = "consultaTramitacion", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTramitacion")
    @ResponseWrapper(localName = "consultaTramitacionResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaTramitacionResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaTramitacionResponse consultaTramitacion(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaTramitacionRequest request
    ) throws RemoteException_Exception;

    @WebMethod(action = "urn:consultaReciboUrbana")
    @Action(input = "urn:consultaReciboUrbana", output = "urn:consultaReciboUrbanaResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:consultaReciboUrbanaRemoteException")})
    @RequestWrapper(localName = "consultaReciboUrbana", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboUrbana")
    @ResponseWrapper(localName = "consultaReciboUrbanaResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaReciboUrbanaResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaObjetoUrbanaResponse consultaReciboUrbana(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaObjetoUrbanaRequest request
    ) throws RemoteException_Exception;

    @WebMethod(operationName = "ConsultaMetadatosResponse", action = "urn:ConsultaMetadatosResponse")
    @Action(input = "urn:ConsultaMetadatosResponse", output = "urn:ConsultaMetadatosResponseResponse", fault = {@FaultAction(className = RemoteException_Exception.class, value = "urn:ConsultaMetadatosResponseRemoteException")})
    @RequestWrapper(localName = "ConsultaMetadatosResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaMetadatosResponse")
    @ResponseWrapper(localName = "ConsultaMetadatosResponseResponse", targetNamespace = "http://ws.gf.gos.greenaall.es", className = "es.greenaall.gos.gf.ws.ConsultaMetadatosResponseResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.gf.gos.greenaall.es")
    public es.greenaall.gos.gf.ws.response.xsd.ConsultaMetadatosResponse consultaMetadatosResponse(

        @WebParam(name = "request", targetNamespace = "http://ws.gf.gos.greenaall.es")
        es.greenaall.gos.gf.ws.request.xsd.ConsultaMetadatosRequest request
    ) throws RemoteException_Exception;
}
