package es.greenaall.gos.gf.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-05T12:16:29.716+01:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "GestionTributos",
                  wsdlLocation = "http://10.234.253.178:8080/GestionTributos/services/GestionTributos?wsdl",
                  targetNamespace = "http://ws.gf.gos.greenaall.es")
public class GestionTributos extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.gf.gos.greenaall.es", "GestionTributos");
    public final static QName GestionTributosHttpEndpoint = new QName("http://ws.gf.gos.greenaall.es", "GestionTributosHttpEndpoint");
    public final static QName GestionTributosHttpSoap12Endpoint = new QName("http://ws.gf.gos.greenaall.es", "GestionTributosHttpSoap12Endpoint");
    public final static QName GestionTributosHttpSoap11Endpoint = new QName("http://ws.gf.gos.greenaall.es", "GestionTributosHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://10.234.253.178:8080/GestionTributos/services/GestionTributos?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionTributos.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.234.253.178:8080/GestionTributos/services/GestionTributos?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionTributos(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionTributos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionTributos() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionTributos(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionTributos(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionTributos(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpEndpoint")
    public GestionTributosPortType getGestionTributosHttpEndpoint() {
        return super.getPort(GestionTributosHttpEndpoint, GestionTributosPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpEndpoint")
    public GestionTributosPortType getGestionTributosHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(GestionTributosHttpEndpoint, GestionTributosPortType.class, features);
    }


    /**
     *
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpSoap12Endpoint")
    public GestionTributosPortType getGestionTributosHttpSoap12Endpoint() {
        return super.getPort(GestionTributosHttpSoap12Endpoint, GestionTributosPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpSoap12Endpoint")
    public GestionTributosPortType getGestionTributosHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(GestionTributosHttpSoap12Endpoint, GestionTributosPortType.class, features);
    }


    /**
     *
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpSoap11Endpoint")
    public GestionTributosPortType getGestionTributosHttpSoap11Endpoint() {
        return super.getPort(GestionTributosHttpSoap11Endpoint, GestionTributosPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionTributosPortType
     */
    @WebEndpoint(name = "GestionTributosHttpSoap11Endpoint")
    public GestionTributosPortType getGestionTributosHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(GestionTributosHttpSoap11Endpoint, GestionTributosPortType.class, features);
    }

}
