
package es.greenaall.gos.gf.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-05T12:16:29.590+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "RemoteException", targetNamespace = "http://ws.gf.gos.greenaall.es")
public class RemoteException_Exception extends java.lang.Exception {

    private es.greenaall.gos.gf.ws.RemoteException faultInfo;

    public RemoteException_Exception() {
        super();
    }

    public RemoteException_Exception(String message) {
        super(message);
    }

    public RemoteException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RemoteException_Exception(String message, es.greenaall.gos.gf.ws.RemoteException remoteException) {
        super(message);
        this.faultInfo = remoteException;
    }

    public RemoteException_Exception(String message, es.greenaall.gos.gf.ws.RemoteException remoteException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = remoteException;
    }

    public es.greenaall.gos.gf.ws.RemoteException getFaultInfo() {
        return this.faultInfo;
    }
}
