Usuario = ${CONFIG_USUARIO}
PassWord = ${CONFIG_PASSWORD}
Entidad = ${CONFIG_ENTIDAD:1}
Provincia = ${CONFIG_PROVINCIA}
Municipio = ${CONFIG_MUNICIPIO}
Ciudad = ${CONFIG_CIUDAD}
NombreEntidad = ${CONFIG_NOMBRE_ENTIDAD}
Certificado = ${CONFIG_CERTIFICADO_PATH}
Verificador = ${CONFIG_VERIFICADOR_URL}
GestionTributos = ${CONFIG_GESTION_TRIBUTOS_URL}
UrlSedeNotificacion = ${CONFIG_URL_SEDE_NOTIFICACION}
